### PR TITLE
Simle web scraper

### PR DESCRIPTION
**Pull request by acgrdumlu**

### CODE REVIEW

**Comment by MadhavBahlMD** [comment]
Awesome!
I will review your code and merge it after that.

**Comment by MadhavBahlMD** [comment]
Hey @acgrdumlu, commit the code again removing the sub module.
your code is not accessible.

**Comment by MadhavBahlMD** [comment]
Try removing that git folder from within that 17-web-scrape folder.

**Comment by acgrdumlu** [comment]
Sorry for late response! I created pull request after the removing git folder. So could you please check the code again.

**Comment by MadhavBahlMD** [comment]
Yeah sure!

**Pull request merged**
